# Generated by Django 5.0.1 on 2024-03-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksmapper',
            name='short',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
